### ISSUE TITLE
Unit tests failing due to different clang/env vars

### ISSUE THREAD

**Issue by drahnr** [paritytech/sccache#23] opened 2020-11-20 10:08 UTC
Some unit tests depend on the particular version of clang.

I.e. https://github.com/paritytech/sccache/pull/22/commits/2db8e2864d6dba1cb925eb9d7d84f5fdbf5ab27a is necessary since clang 7.x in an old ubuntu container exposes different behaviour than the clang 11.x shipped with fedora 33. This might also be partly due to the default env flags.

TODO:

* [ ] investigate the true reason for the different behaviour
    * [ ] compare env vars
    * [ ] test behviour with identical env vars on different clang version

**Comment by TriplEight** [comment] 2020-12-11 17:30
Our CI image [ships](https://gitlab.parity.io/parity/infrastructure/scripts/-/jobs/744948#L2058) with `Ubuntu clang version 11.0.0-2`

Here you can take a look of the whole pipeline for building and testing the CI image.

Also, to add to this issue, red CI blocks us from having ci images being updated regularly.

**Comment by Xanewok** [comment] 2021-03-25 02:51
I have the exact version as @TriplEight posted but I couldn't reproduce locally when working on https://github.com/paritytech/sccache/pull/33 (had to add a workaroundaround in https://github.com/paritytech/sccache/pull/33/commits/edce5ab1a4eb5293a356f371207ea85b0730782f#diff-5bf851c60481a580af29ec90f0a321f163ac8510fd20a82da09f21bb9b07ba52)

**Comment by drahnr** [comment] 2021-03-25 10:16
There are two issues I see: The clang version is still the old one in the nightly version and the clang and gcc versions are not printed for the stable version.

**Comment by TriplEight** [comment] 2021-03-25 14:18
Do you mean clang/gcc in the nightly version of what? Rust? How can this be?

**Comment by drahnr** [comment] 2021-03-25 14:27
I am talking about the containers used for the nightly and stable test env.

**Comment by TriplEight** [comment] 2021-03-25 15:17
Ah damn, that's because the [`before_script:`](https://github.com/paritytech/sccache/blob/master/.gitlab-ci.yml#L26) that would show the versions is [rewritten](https://github.com/paritytech/sccache/blob/master/.gitlab-ci.yml#L88) in the stable job. Will fix.

As for "still". I've set up a fancy CI for the image, it's being nightly tested against the `master` branch. But perhaps it was a bit premature. First, we should've made the CI green. Will fix as well, temporarily switching to `staging` tag.

**Comment by Xanewok** [comment] 2021-03-25 20:31
To add a data point:
- https://github.com/paritytech/sccache/pull/33 (https://gitlab.parity.io/parity/sccache/-/pipelines/130448) fails on nightly-test but works on stable-test
- https://github.com/paritytech/sccache/pull/34 (https://gitlab.parity.io/parity/sccache/-/pipelines/130645; only adds https://github.com/paritytech/sccache/pull/34/commits/788832be1207fd0a2e5aee65f1c4194300b0fb33 which uses test data from upstream mozilla/sccache) works on nightly-test but fails on stable-test

Locally I'm seeing tests passing with #34, both with `cargo +stable test` (rustc 1.51) and `cargo +nightly test` (rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
I'm on Ubuntu 20.10 and using:
```bash
# clang --version
Ubuntu clang version 11.0.0-2
# gcc --version
gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
```

(@drahnr despite the mismatched runs, it seems that with #33, the futures migration branch is able to pass remaining tests :tada: )

**Comment by drahnr** [comment] 2021-03-26 09:10
> Ah damn, that's because the [`before_script:`](https://github.com/paritytech/sccache/blob/master/.gitlab-ci.yml#L26) that would show the versions is [rewritten](https://github.com/paritytech/sccache/blob/master/.gitlab-ci.yml#L88) in the stable job. Will fix.

Thanks!

> As for "still". I've set up a fancy CI for the image, it's being nightly tested against the `master` branch. But perhaps it was a bit premature. First, we should've made the CI green. Will fix as well, temporarily switching to `staging` tag.

"Still" as in I was under the impression that we solved this already a couple of months ago :upside_down_face:

**Comment by TriplEight** [comment] 2021-03-26 16:09
https://github.com/paritytech/sccache/pull/35
also added more detailed statuses from GitLab CI.

**Comment by Xanewok** [comment] 2021-03-27 18:50
I'm confused - it seems that #33 still [fails](https://gitlab.parity.io/parity/sccache/-/pipelines/130962) on `stable-test` but I cherry-picked the CI update (`git diff origin/master HEAD .gitlab-ci.yml` reports nothing) as well.
I verified it locally, inside a Docker container that's using the staging image (same ID as the one in the runs, so same clang/gcc version etc.):
```
xanewok@faerun-dev:~/repos/sccache (igor-futures-fixes)$ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
paritytech/sccache-ci-ubuntu   staging             ef237daac623        12 hours ago        2.14GB
```
with respective commands from
- https://gitlab.parity.io/parity/sccache/-/jobs/870540/raw and
- https://gitlab.parity.io/parity/sccache/-/jobs/870541/raw

and everything seems to be working fine. Do you have any ideas why does it fail during the CI run?

**Comment by drahnr** [comment] 2021-03-30 11:43
We should look into which versions of container/clang/gcc/rustc are used for the CI run, and that should be already extractable since at least yesterday.

If this is indeed sporadic, then we should add bounds check rather than a specific number for now or investigate further which calls do not succeed.

`podman run -v $(PWD):/workdir -w /workdir --rm -it ubuntu:groovy cargo test` (and replacing `ubuntu` with the ci env container) should give a decent reproducability chance

**Comment by TriplEight** [comment] 2021-03-30 18:03
@Xanewok [restarted](https://gitlab.parity.io/parity/sccache/-/jobs/877082) your job. Now it found a different reason to fail on an updated nightly CI image.

**Comment by drahnr** [comment] 2021-03-31 09:08
```
[2021-03-31T05:18:32Z TRACE system] run_sccache_command_test: gcc
[2021-03-31T05:18:32Z TRACE system] fs::copy("tests/test.c", "/tmp/sccache_system_test45QoOR/test.c")
[2021-03-31T05:18:32Z TRACE system] fs::copy("tests/test_err.c", "/tmp/sccache_system_test45QoOR/test_err.c")
[2021-03-31T05:18:32Z TRACE system] compile
[2021-03-31T05:18:32Z TRACE system] request stats
thread 'test_sccache_command' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', tests/system.rs:119:9
stack backtrace:
```

still pops up, gcc is version `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`, but isn't `ubuntu:groovy` equiv to `ubuntu:20.10` :monocle_face:

**Comment by TriplEight** [comment] 2021-04-01 14:51
`gcc` is indeed different between 20.10 and 20.04. And with the last refactor I've moved to base off `base-ci` [on 20.04](https://github.com/paritytech/scripts/blob/master/dockerfiles/base-ci/Dockerfile#L1). Does it make difference? Never saw a requirement for a concrete version.

**Comment by drahnr** [comment] 2021-04-01 14:54
No, but there should be some consistency and an agreed change of base. The last thing I reviewed was using `ubuntu:groovy` hence my confusion.

**Comment by TriplEight** [comment] 2021-04-01 15:47
Then I think we can settle here, on the LTS.

**Comment by Xanewok** [comment] 2021-04-02 15:46
Well, moving target or not, what's very weird is that I tried to reproduce the exact CI run locally (in https://github.com/paritytech/sccache/issues/23#issuecomment-808785842; same Docker image/sha, hence same environment, gcc, rust etc. versions) and the CI failed while I was getting consistently good results locally, which at this point means that the only difference between those was the host environment and resources, unless I'm missing something.

Maybe some file stomping has occurred and somehow my machine did something faster and didn't notice a corrupt state in between or the other way around? This is me guessing but I'd love to know why the results were different even though gcc, guest os etc. was exactly the same.

**Comment by TriplEight** [comment] 2021-04-06 15:12
even though you ran the same image, there still could be some differences: to reproduce CI locally one shouldn't forget about the [defaults](https://github.com/paritytech/sccache/blob/master/.gitlab-ci.yml#L14) and that CI also redirects the `CARGO_HOME` and `CARGO_TARGET_DIR` to the persistent volume.
I wrote a small script to run it locally easier:
```
#!/bin/bash

# Cargo as a virtual environment in the current dir
  dirname="$(basename $(pwd))"
  user=$(whoami)
  echo "Cargo as a virtual environment in" "$dirname" "dir"
  mkdir -p /home/"$user"/cache/"$dirname"
  podman run --rm -it -w /shellhere/"$dirname" -v "$(pwd)":/shellhere/"$dirname" -v /home/"$user"/cache/"$dirname"/:/cache/ -e CARGO_HOME=/cache/cargo/ -e SCCACHE_DIR=/cache/sccache/ -e CARGO_TARGET_DIR=/cache/target/ "$@"

# example
# cargoenvhere paritytech/ci-linux:production /bin/bash -c 'RUSTFLAGS="-Cdebug-assertions=y -Dwarnings" RUST_BACKTRACE=1 time cargo test --workspace --locked --release --verbose --features runtime-benchmarks --manifest-path bin/node/cli/Cargo.toml'⏎
```

Also wrote a function for fish, can share.

**Comment by Xanewok** [comment] 2021-04-07 17:28
Thanks! Indeed, the underlying issue was caused by default `CARGO_INCREMENTAL` set to 0 and `SCCACHE_REDIS` set in our CI.

Fixed by https://github.com/paritytech/sccache/pull/42.

**Closed by Xanewok** 2021-04-07 17:28 UTC
Labels: CI, bug
